[project]
name = "pipeline-databricks-lakehouse"
version = "0.1.0"
description = "Pipeline de Engenharia de Dados com Databricks e Delta Lake"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "requests",
    "pyspark",
    "pytest",
    "requests-mock",
]

[tool.pytest.ini_options]
pythonpath = ["src"]

[tool.ruff]
builtins = ["spark", "dbutils", "display"]
line-length = 88
target-version = "py310"

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
]
ignore = []
[tool.ruff.format]
quote-style = "double"
indent-style = "space"
